### ISSUE TITLE
two-ish comments regarding generator

### ISSUE THREAD

**Issue by hc5duke** [Tapjoy/acts_as_approvable#4]
1. `object` is of type `varchar(255)` - this could run into issues if an attribute value is really long
2. `item_id` and `owner_id` are of type `integer` - wouldn't work with our system -- I guess this wouldn't be an issue if we didn't use the generator and run our own migration though.

Also, what's the purpose of `owner`?

**Comment by jlogsdon** [comment]
Hmm... `object` should definitely be a `text` field. I'll have to check that out.

Because the generator doesn't actually run the migration you can easily change the `owner_id` and `item_id` to guids or whatever type you need.

`owner` is an optional relationship that allows you to assign a `User` (or whatever model you use for accounts, which is why its polymorphic: I don't know of a good way to allow configuration of the relationship... though I have some thoughts on that) that should handle the approval. When I finish the controller it will also change the `owner` to whoever does the approval or rejection of the changes. It's mostly for tracking purposes, and is entirely optional.

**update** `object` is getting created as a `text` for me, with both sqlite and mysql. I did need to fix the default for `state`, though.

**Comment by jlogsdon** [comment]
I'm going to close this. I haven't been able to replicate the `object` as `varchar(255)` issue, and I've cleaned up the `owner` relationship so it's handled in the generator now (and is completely optional). Check it out in bd786ae3.

**Comment by hc5duke** [comment]
Yeah that's fine - text is varchar(255) in mysql AFAIK, but like you said, you don't have to run the migration file generated by the script.
